---
title: "Assigment 3"
author: "Raveena John"
date: "9/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
library(ggthemes)
library(ggspatial)
library(units)
library(nngeo)
```

```{r}
wifi <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/6a7a0ab4e964471f819d40078b17e7fa_0.kml?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D", 
                  quiet = TRUE) 

open <- st_read("http://bostonopendata-boston.opendata.arcgis.com/datasets/2b3c0fa13b1c468eb702a3645fcc6bcb_5.kml", 
                 quiet = TRUE)

centers <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/acedd06b39854088b0f2fefccffebf84_0.kml?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D", 
                   quiet = TRUE) 

main <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/440c7ec0178d4c8593aecef7ea96bb4d_0.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D", 
                 quiet = TRUE) 
```

```{r}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

wifi <- wifi %>%
  st_transform(MA_state_plane)

open <- open %>%
  st_transform(MA_state_plane)

centers <- centers %>%
  st_transform(MA_state_plane)

main <- main %>%
  st_transform(MA_state_plane)
```

